# Generated by Django 4.2.10 on 2024-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
