# Generated by Django 4.2.10 on 2024-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_room_name_delete_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Join',
            field=models.CharField(default='DDU', max_length=1000),
            preserve_default=False,
        ),
    ]
