# Generated by Django 4.2.10 on 2024-02-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_room_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group_icon',
            field=models.ImageField(blank=True, null=True, upload_to='group_icons/'),
        ),
    ]
