# Generated by Django 4.2.10 on 2024-02-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_group_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='group_icon',
        ),
        migrations.AddField(
            model_name='room',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
