# Generated by Django 4.2.10 on 2024-02-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_room_group_icon_room_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='icon',
        ),
    ]
