# Generated by Django 4.2.10 on 2024-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_room_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
       field=models.CharField(default='', max_length=50),
        ),
    ]
