# Generated by Django 4.2.10 on 2024-02-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Join',
        ),
    ]
